overrides:
  esbuild: '>=0.24.3'
  postcss: '>=8.5.10'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@vercel/speed-insights': true
  esbuild: true
  sharp: true
  unrs-resolver: true
